// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.stationmillenium.coverart.domain.statuses;

import com.stationmillenium.coverart.domain.statuses.PlaylistStatus;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect PlaylistStatus_Roo_Configurable {
    
    declare @type: PlaylistStatus: @Configurable;
    
}
