// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.stationmillenium.coverart.domain.statuses;

import com.stationmillenium.coverart.domain.statuses.ServerStatus;
import javax.persistence.Entity;

privileged aspect ServerStatus_Roo_Jpa_Entity {
    
    declare @type: ServerStatus: @Entity;
    
}
