// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.stationmillenium.coverart.domain;

import com.stationmillenium.coverart.domain.ServerStatusDataOnDemand;
import com.stationmillenium.coverart.domain.ServerStatusIntegrationTest;
import com.stationmillenium.coverart.domain.statuses.ServerStatus;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ServerStatusIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ServerStatusIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ServerStatusIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ServerStatusIntegrationTest: @Transactional;
    
    @Autowired
    private ServerStatusDataOnDemand ServerStatusIntegrationTest.dod;
    
    @Test
    public void ServerStatusIntegrationTest.testCountServerStatuses() {
        Assert.assertNotNull("Data on demand for 'ServerStatus' failed to initialize correctly", dod.getRandomServerStatus());
        long count = ServerStatus.countServerStatuses();
        Assert.assertTrue("Counter for 'ServerStatus' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ServerStatusIntegrationTest.testFindServerStatus() {
        ServerStatus obj = dod.getRandomServerStatus();
        Assert.assertNotNull("Data on demand for 'ServerStatus' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ServerStatus' failed to provide an identifier", id);
        obj = ServerStatus.findServerStatus(id);
        Assert.assertNotNull("Find method for 'ServerStatus' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ServerStatus' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ServerStatusIntegrationTest.testFindAllServerStatuses() {
        Assert.assertNotNull("Data on demand for 'ServerStatus' failed to initialize correctly", dod.getRandomServerStatus());
        long count = ServerStatus.countServerStatuses();
        Assert.assertTrue("Too expensive to perform a find all test for 'ServerStatus', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ServerStatus> result = ServerStatus.findAllServerStatuses();
        Assert.assertNotNull("Find all method for 'ServerStatus' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ServerStatus' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ServerStatusIntegrationTest.testFindServerStatusEntries() {
        Assert.assertNotNull("Data on demand for 'ServerStatus' failed to initialize correctly", dod.getRandomServerStatus());
        long count = ServerStatus.countServerStatuses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ServerStatus> result = ServerStatus.findServerStatusEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ServerStatus' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ServerStatus' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ServerStatusIntegrationTest.testFlush() {
        ServerStatus obj = dod.getRandomServerStatus();
        Assert.assertNotNull("Data on demand for 'ServerStatus' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ServerStatus' failed to provide an identifier", id);
        obj = ServerStatus.findServerStatus(id);
        Assert.assertNotNull("Find method for 'ServerStatus' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyServerStatus(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'ServerStatus' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ServerStatusIntegrationTest.testMergeUpdate() {
        ServerStatus obj = dod.getRandomServerStatus();
        Assert.assertNotNull("Data on demand for 'ServerStatus' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ServerStatus' failed to provide an identifier", id);
        obj = ServerStatus.findServerStatus(id);
        boolean modified =  dod.modifyServerStatus(obj);
        Integer currentVersion = obj.getVersion();
        ServerStatus merged = (ServerStatus)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ServerStatus' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ServerStatusIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ServerStatus' failed to initialize correctly", dod.getRandomServerStatus());
        ServerStatus obj = dod.getNewTransientServerStatus(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ServerStatus' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ServerStatus' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'ServerStatus' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ServerStatusIntegrationTest.testRemove() {
        ServerStatus obj = dod.getRandomServerStatus();
        Assert.assertNotNull("Data on demand for 'ServerStatus' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ServerStatus' failed to provide an identifier", id);
        obj = ServerStatus.findServerStatus(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ServerStatus' with identifier '" + id + "'", ServerStatus.findServerStatus(id));
    }
    
}
