// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.stationmillenium.coverart.domain;

import com.stationmillenium.coverart.domain.SongHistory;
import com.stationmillenium.coverart.domain.SongHistoryDataOnDemand;
import com.stationmillenium.coverart.domain.SongHistoryIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SongHistoryIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SongHistoryIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SongHistoryIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SongHistoryIntegrationTest: @Transactional;
    
    @Autowired
    private SongHistoryDataOnDemand SongHistoryIntegrationTest.dod;
    
    @Test
    public void SongHistoryIntegrationTest.testCountSongHistorys() {
        Assert.assertNotNull("Data on demand for 'SongHistory' failed to initialize correctly", dod.getRandomSongHistory());
        long count = SongHistory.countSongHistorys();
        Assert.assertTrue("Counter for 'SongHistory' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SongHistoryIntegrationTest.testFindSongHistory() {
        SongHistory obj = dod.getRandomSongHistory();
        Assert.assertNotNull("Data on demand for 'SongHistory' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SongHistory' failed to provide an identifier", id);
        obj = SongHistory.findSongHistory(id);
        Assert.assertNotNull("Find method for 'SongHistory' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'SongHistory' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void SongHistoryIntegrationTest.testFindAllSongHistorys() {
        Assert.assertNotNull("Data on demand for 'SongHistory' failed to initialize correctly", dod.getRandomSongHistory());
        long count = SongHistory.countSongHistorys();
        Assert.assertTrue("Too expensive to perform a find all test for 'SongHistory', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<SongHistory> result = SongHistory.findAllSongHistorys();
        Assert.assertNotNull("Find all method for 'SongHistory' illegally returned null", result);
        Assert.assertTrue("Find all method for 'SongHistory' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SongHistoryIntegrationTest.testFindSongHistoryEntries() {
        Assert.assertNotNull("Data on demand for 'SongHistory' failed to initialize correctly", dod.getRandomSongHistory());
        long count = SongHistory.countSongHistorys();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<SongHistory> result = SongHistory.findSongHistoryEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'SongHistory' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'SongHistory' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SongHistoryIntegrationTest.testFlush() {
        SongHistory obj = dod.getRandomSongHistory();
        Assert.assertNotNull("Data on demand for 'SongHistory' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SongHistory' failed to provide an identifier", id);
        obj = SongHistory.findSongHistory(id);
        Assert.assertNotNull("Find method for 'SongHistory' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifySongHistory(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'SongHistory' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SongHistoryIntegrationTest.testMergeUpdate() {
        SongHistory obj = dod.getRandomSongHistory();
        Assert.assertNotNull("Data on demand for 'SongHistory' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SongHistory' failed to provide an identifier", id);
        obj = SongHistory.findSongHistory(id);
        boolean modified =  dod.modifySongHistory(obj);
        Integer currentVersion = obj.getVersion();
        SongHistory merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'SongHistory' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SongHistoryIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'SongHistory' failed to initialize correctly", dod.getRandomSongHistory());
        SongHistory obj = dod.getNewTransientSongHistory(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'SongHistory' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'SongHistory' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'SongHistory' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void SongHistoryIntegrationTest.testRemove() {
        SongHistory obj = dod.getRandomSongHistory();
        Assert.assertNotNull("Data on demand for 'SongHistory' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SongHistory' failed to provide an identifier", id);
        obj = SongHistory.findSongHistory(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'SongHistory' with identifier '" + id + "'", SongHistory.findSongHistory(id));
    }
    
}
