// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.stationmillenium.coverart.domain;

import com.stationmillenium.coverart.domain.SongItemDataOnDemand;
import com.stationmillenium.coverart.domain.SongItemIntegrationTest;
import com.stationmillenium.coverart.domain.history.SongItem;

import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SongItemIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SongItemIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SongItemIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SongItemIntegrationTest: @Transactional;
    
    @Autowired
    private SongItemDataOnDemand SongItemIntegrationTest.dod;
    
    @Test
    public void SongItemIntegrationTest.testCountSongItems() {
        Assert.assertNotNull("Data on demand for 'SongItem' failed to initialize correctly", dod.getRandomSongItem());
        long count = SongItem.countSongItems();
        Assert.assertTrue("Counter for 'SongItem' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SongItemIntegrationTest.testFindSongItem() {
        SongItem obj = dod.getRandomSongItem();
        Assert.assertNotNull("Data on demand for 'SongItem' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SongItem' failed to provide an identifier", id);
        obj = SongItem.findSongItem(id);
        Assert.assertNotNull("Find method for 'SongItem' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'SongItem' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void SongItemIntegrationTest.testFindAllSongItems() {
        Assert.assertNotNull("Data on demand for 'SongItem' failed to initialize correctly", dod.getRandomSongItem());
        long count = SongItem.countSongItems();
        Assert.assertTrue("Too expensive to perform a find all test for 'SongItem', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<SongItem> result = SongItem.findAllSongItems();
        Assert.assertNotNull("Find all method for 'SongItem' illegally returned null", result);
        Assert.assertTrue("Find all method for 'SongItem' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SongItemIntegrationTest.testFindSongItemEntries() {
        Assert.assertNotNull("Data on demand for 'SongItem' failed to initialize correctly", dod.getRandomSongItem());
        long count = SongItem.countSongItems();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<SongItem> result = SongItem.findSongItemEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'SongItem' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'SongItem' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SongItemIntegrationTest.testFlush() {
        SongItem obj = dod.getRandomSongItem();
        Assert.assertNotNull("Data on demand for 'SongItem' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SongItem' failed to provide an identifier", id);
        obj = SongItem.findSongItem(id);
        Assert.assertNotNull("Find method for 'SongItem' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifySongItem(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'SongItem' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SongItemIntegrationTest.testMergeUpdate() {
        SongItem obj = dod.getRandomSongItem();
        Assert.assertNotNull("Data on demand for 'SongItem' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SongItem' failed to provide an identifier", id);
        obj = SongItem.findSongItem(id);
        boolean modified =  dod.modifySongItem(obj);
        Integer currentVersion = obj.getVersion();
        SongItem merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'SongItem' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SongItemIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'SongItem' failed to initialize correctly", dod.getRandomSongItem());
        SongItem obj = dod.getNewTransientSongItem(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'SongItem' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'SongItem' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'SongItem' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void SongItemIntegrationTest.testRemove() {
        SongItem obj = dod.getRandomSongItem();
        Assert.assertNotNull("Data on demand for 'SongItem' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SongItem' failed to provide an identifier", id);
        obj = SongItem.findSongItem(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'SongItem' with identifier '" + id + "'", SongItem.findSongItem(id));
    }
    
}
