// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.stationmillenium.coverart.domain.statuses.abstracts;

import com.stationmillenium.coverart.domain.statuses.abstracts.AbstractStatus;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect AbstractStatus_Roo_Configurable {
    
    declare @type: AbstractStatus: @Configurable;
    
}
