// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.stationmillenium.coverart.domain.alert;

import com.stationmillenium.coverart.domain.alert.AlertActivation;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect AlertActivation_Roo_Configurable {
    
    declare @type: AlertActivation: @Configurable;
    
}
